### ISSUE TITLE
Running .prefix by itself causes a crash

### ISSUE THREAD

**Issue by S-B99** [S-B99/KAMI#111]
Running just `.prefix` without anything else causes a crash. Not sure why this is

**Comment by S-B99** [comment]
@zeroeightysix if you have any insight on this it would be appriciated

**Comment by S-B99** [comment]
```java
        if (args.length == 0) {
            Command.sendChatMessage("Please specify a new prefix!");
            return;
        }
```
this is supposed to run but it doesn't

**Comment by cookiedragon234** [comment]
Is this the nullpointer you were talking about?

Have you tried
`if(args==null || args.length <= 0)`

**Comment by S-B99** [comment]
No, I get an NPE when joining singleplayer worlds sometimes. I think 086 fixed it in d6f789f30517545335252f1da424cbbd7ba9396f

**Comment by d1gress** [comment]
args most likely does not have a length if it is never initiated with a length
try using cookie's solution

**Comment by zeroeightysix** [comment]
What's the error? Can you provide a full crash log?

**Comment by S-B99** [comment]
[latest.log](https://github.com/S-B99/KAMI/files/3883076/latest.log)
[debug.log](https://github.com/S-B99/KAMI/files/3883077/debug.log)
That would've been a good idea, sorry

**Comment by zeroeightysix** [comment]
I guess on this line, `Command.getCommandPrefix()` returns null:
https://github.com/S-B99/KAMI/blob/da2ff767f9cff6fc0dcb635460ac966508e4057e/src/main/java/me/zeroeightsix/kami/gui/mc/KamiGuiChat.java#L37
Suggesting that `.prefix` set the prefix to `args[0]` which is `null` because no arguments were supplied?
