### ISSUE TITLE
color picker for holeesp

### ISSUE THREAD

**Issue by decendium** [S-B99/KAMI#114]
make a color wheel if you right click on HoleEsp where you can choose any RGB color and maybe if you want different colors for bedrock and obsidian have 2 different color wheels to choose colors for each one

**Comment by S-B99** [comment]
Duplicate of #106 and pull #113

**Comment by S-B99** [comment]
I'll close when 113 is done

**Comment by S-B99** [comment]
closed in commit 058e9b49826a81cbc8fbfd925c2972ae6a779a45
