### ISSUE TITLE
more HoleESP options

### ISSUE THREAD

**Issue by decendium** [S-B99/KAMI#115]
make an option to show bottoms and not fill the whole block in;
an option to do this:
![1](https://cdn.discordapp.com/attachments/634010802403409931/647887391767396356/unknown.png)
and an option to do this:
![2](https://cdn.discordapp.com/attachments/634010802403409931/647887474986713108/unknown.png)

**Comment by blockparole** [comment]
Thats basically what i pred [here](https://github.com/zeroeightysix/KAMI/pull/142).

**Comment by Crystallinqq** [comment]
shut up

**Comment by cookiedragon234** [comment]
🤥

**Comment by decendium** [comment]
> shut up

my simple answer is

no

**Comment by Crystallinqq** [comment]
my simple answer is 

shut up default pfp

**Comment by Crystallinqq** [comment]
bella is gay

**Comment by S-B99** [comment]
That I am. Can we keep this on topic?

**Comment by Crystallinqq** [comment]
no we may not
