### ISSUE TITLE
Gui Modification

### ISSUE THREAD

**Issue by RicardoThanos** [S-B99/KAMI#116]
You should be able to resize/modify the GUI because sometimes just pressing Y will cover your entire screen and even some categories go offscreen

Make the GUI resizable by a modules/option button or something like that

I have tried putting the all the categories near eachother to makes space but that just fucks it up

**Comment by S-B99** [comment]
Duplicate of #68

**Comment by S-B99** [comment]
Change your Minecraft GUI size to smaller for now
