### ISSUE TITLE
Tick delay for surround can go into the negatives

### ISSUE THREAD

**Issue by Deauthorized** [S-B99/KAMI#127]
**Describe the bug**
blocks per tick in surround goes into the negatives

**To Reproduce**
1. Go to 'surround'
2. Click on 'blocks per tick'
3. Scroll down to 'some value under 0'
4. See that it does nothing until the value is raised above 0 again

**Expected behavior**
doesn't go into the negatives

**Screenshots**

![image](https://user-images.githubusercontent.com/49701242/69505310-4aa10900-0ef7-11ea-80ac-4aec8d04798a.png)

**Additional context**
naw

**Comment by S-B99** [comment]
Solution: make this a slider
