### ISSUE TITLE
Using \ as a prefix causes a crash

### ISSUE THREAD

**Issue by S-B99** [S-B99/KAMI#146]

**Comment by Deauthorized** [comment]
fix: dont

**Comment by Quazar5** [comment]
lol ok ok!

**Comment by S-B99** [comment]
![Screenshot_20191125_194806](https://user-images.githubusercontent.com/17222512/69590249-daf55180-0fbc-11ea-90db-3b9a7f88911e.png)

**Comment by S-B99** [comment]
This is the new system btw

![Screenshot_20191126_080221](https://user-images.githubusercontent.com/17222512/69635756-204c6a00-1023-11ea-991c-cea0a2f322f1.png)
