### ISSUE TITLE
AutoQMain change disabling to a warning you're not on 2b

### ISSUE THREAD

**Issue by S-B99** [S-B99/KAMI#160]

**Comment by snowmii** [comment]
just don't send message if you're not at 0 240 0

**Comment by Deauthorized** [comment]
> 
> 
> just don't send message if you're not at 0 240 0

why would you do that and risk false triggering when you can just do that s-b99 is doing

**Comment by snowmii** [comment]
`
package me.zeroeightsix.kami.module.modules.misc;

import me.zeroeightsix.kami.module.Module;
import me.zeroeightsix.kami.module.ModuleManager;
import me.zeroeightsix.kami.command.Command;
import me.zeroeightsix.kami.setting.Setting;
import me.zeroeightsix.kami.setting.Settings;
import net.minecraft.client.Minecraft;
import net.minecraft.network.play.client.CPacketChatMessage;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.util.math.Vec3i;

/**
 * Created by d1gress/Qther on 24/11/2019.
 * Updated by @S-B99 on 25/11/19
 */
@Module.Info(name = "AutoQMain", description = "Automatically does \"/queue main\" every 7.1 minutes.", category = Module.Category.MISC)
public class AutoQMain extends Module {

    private Setting<Boolean> debug = register(Settings.b("Debug", true));
    static final Minecraft mc = Minecraft.getMinecraft();
    private static long startTime = 0;

    @Override
    public void onUpdate() {
        if (mc.player == null) {
            return;
        }
        if (mc.player.dimension == 1&&mc.player.getPosition().equals(new Vec3i(0, 240, 0)) && mc.getCurrentServerData().serverIP.equalsIgnoreCase("2b2t.org"))) {
            if (startTime == 0 || startTime <= System.currentTimeMillis() - 427000) startTime = System.currentTimeMillis();
            if (startTime + 426000 <= System.currentTimeMillis()) {
                if (debug.getValue()) {
                    Command.sendChatMessage("&7Run &b/queue main&7 at " + System.currentTimeMillis());
                }
                Minecraft.getMinecraft().playerController.connection.sendPacket(new CPacketChatMessage("/queue main"));
                Command.sendChatMessage("Sent \"/queue main\" at " + System.currentTimeMillis());
                startTime = System.currentTimeMillis();
            }
        }
    }
}`

**Comment by snowmii** [comment]
bruh im so unfamiliar with github
