### ISSUE TITLE
Color Wheel for anything using colors [ESP, Storage ESP, Tracers, Other things like that.

### ISSUE THREAD

**Issue by RicardoThanos** [S-B99/KAMI#166]
**Is your feature request related to a problem? Please describe.**
When I use StorageESP All chests and shulkers are the same and it makes me the big confusion.

**Describe the solution you'd like**
Adding an RGB Color Wheel/Square to change colors of any ESP or something using color

**Describe alternatives you've considered**
I tried using other ESP mods but they are all shit

**Additional context**
Adding color wheel for:
Tracers
Trajectories
ESP
Storage ESP
Others like that

**Comment by S-B99** [comment]
Sliders not wheel

**Comment by RicardoThanos** [comment]
yea

**Comment by S-B99** [comment]
And that's not what context mean either.
That would require different modes for esp as well

**Comment by S-B99** [comment]
Also in the future please use seperate issues for seperate features

**Comment by RicardoThanos** [comment]
ok
