### ISSUE TITLE
Move AutoWalk and AutoJump from "Player" to "Movement"

### ISSUE THREAD

**Issue by Fu-ms** [S-B99/KAMI#178]
**Describe the bug**
Move AutoWalk and AutoJump from "Player" to "Movement"

**Expected behavior**
AutoWalk and AutoJump to be in Movement section.

**Additional context**
Refactor it into movement, takes 5 seconds.

**Comment by S-B99** [comment]
> bug

**Comment by Fu-ms** [comment]
kek, didnt know where to put it. Techinically it is a bug as its supposed to be in movement :P

**Comment by S-B99** [comment]
I mean, it's not broken, it's an enhancement really lol
