### ISSUE TITLE
Solution if noFall doesn't work (on master branch)

### ISSUE THREAD

**Issue by S-B99** [S-B99/KAMI#19]
https://github.com/S-B99/KAMI/commit/1dfd30444b280188d1a37353b320b11f108b4816

https://github.com/zeroeightysix/KAMI/pull/114#issuecomment-538749878

change posvec to pos

**Comment by mrx12335** [comment]
F

**Comment by S-B99** [comment]
Scaffold works on origin/update-gradlew

Leaving this open in case it's broken on master

**Comment by S-B99** [comment]
NoFall works on features-master and closing as master will be replaced with this
