### ISSUE TITLE
ReverseScaffold

### ISSUE THREAD

**Issue by DontEatOreo** [S-B99/KAMI#194]
As title says ReverseScaffold instead of going up you go down with it.

**Comment by S-B99** [comment]
You mean break the block under you?

**Comment by DontEatOreo** [comment]
No. What I mean is it scaffolds but instead of placing blocks in front of you or going up with it, it places blocks only below you so u don't have to manually place blocks in freecam to go downwards.

**Comment by d1gress** [comment]
downwards staircase scaffold essentially

**Comment by DontEatOreo** [comment]
> 
> 
> downwards staircase scaffold essentially

Yea.

**Comment by S-B99** [comment]
Just turn on nofall

**Comment by S-B99** [comment]
Honestly too much work for something i've never heard of and is almost useless

**Comment by DontEatOreo** [comment]
> 
> 
> Just turn on nofall

it could be useful in case where you can't use nofall and jumping down would take too much damage.

**Comment by S-B99** [comment]
Kami is specifically made for

> anarchy servers (see readme.md)

And this implies either nofall works or you have totems / gapps

**Comment by d1gress** [comment]
ill try make it if i ever learn Facing and block placements

**Comment by S-B99** [comment]
I mean, I can teach your those on discord if you really want to. Just saying it's essentially useless but I'll appreciate it as a plugin
