### ISSUE TITLE
Drag Settings boxes in clickgui

### ISSUE THREAD

**Issue by d1gress** [S-B99/KAMI#201]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
be able to drag settings boxes

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by S-B99** [comment]
But why

**Comment by d1gress** [comment]
example if a module is at the bottom of the screen then i cant change settings

**Comment by S-B99** [comment]
I'm pretty sure it moves the box up to fit

**Comment by S-B99** [comment]
If not just drag your entire box up

**Comment by d1gress** [comment]
if its meant to then it breaks on large

**Comment by d1gress** [comment]
i cant drag it are you supposed to be able to

**Comment by S-B99** [comment]
You can't drag the settings but you can drag the entire category

**Comment by d1gress** [comment]
small screen problems

**Comment by S-B99** [comment]
Then it's a duplicate of #68 and #99
