### ISSUE TITLE
Auto crystal pvp

### ISSUE THREAD

**Issue by Puffy120** [S-B99/KAMI#207]
It automatically fights for you without you touching your keyboard and wins everytime.

**Comment by S-B99** [comment]
Turn on autocrystal and change the settings to your likings

**Comment by Puffy120** [comment]
I want to pvp without touching my keyboard... That means It automatically moves and plays smart and knows when to do what... xd

**Comment by S-B99** [comment]
Is it that hard to press wasd

**Comment by SpicyBigDaddy-alt** [comment]
Congrats on the worst issue so far puffy
