### ISSUE TITLE
MCP 1.12.2 srg went down, build no longer works

### ISSUE THREAD

**Issue by S-B99** [S-B99/KAMI#21]
The original [url went down ](https://jitpack.io/de/oceanlabs/mcp/mcp/1.12.2/mcp-1.12.2-srg.zip) so I need to use this [url](files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp/1.12.2/mcp-1.12.2-srg.zip) now, or host it on this git repo. 

I can't find anythere referencing how to change it or a url itself.

**Comment by blockparole** [comment]
For me the build fails in a rather different way.
from gradle build log:
```.\KAMI\build\sources\main\java\me\zeroeightsix\kami\command\commands\SetCommand.java:8: error: cannot find symbol
import me.zeroeightsix.kami.setting.ISettingUnknown;
                                   ^
  symbol:   class ISettingUnknown
  location: package me.zeroeightsix.kami.setting
```
->
https://github.com/S-B99/KAMI/blob/eef096473556726138cb0a634dfcfbe06765d3cf/src/main/java/me/zeroeightsix/kami/command/commands/SetCommand.java#L8

but there is no file to import at `me.zeroeightsix.kami.setting.ISettingUnknown`

**Comment by S-B99** [comment]
Offtopic, open a new issue.

**Comment by S-B99** [comment]
Builds now seem to work, however the file is down?. origin/master has assets in case it ever breaks again.
