### ISSUE TITLE
gradle build fails due to import of missing class

### ISSUE THREAD

**Issue by blockparole** [S-B99/KAMI#23]
The build fails for me.
From gradle build log:
```.\KAMI\build\sources\main\java\me\zeroeightsix\kami\command\commands\SetCommand.java:8: error: cannot find symbol
import me.zeroeightsix.kami.setting.ISettingUnknown;
                                   ^
  symbol:   class ISettingUnknown
  location: package me.zeroeightsix.kami.setting
```
->
https://github.com/S-B99/KAMI/blob/eef096473556726138cb0a634dfcfbe06765d3cf/src/main/java/me/zeroeightsix/kami/command/commands/SetCommand.java#L8

but there is no file to import at `me.zeroeightsix.kami.setting.ISettingUnknown`

my build setup:

```
Gradle 5.4.1

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_211 (Oracle Corporation 25.211-b12)
OS:           Windows 10 10.0 amd64

**Comment by blockparole** [comment]
Just posting here for completeness:
This was tested on branch `origin/master`.
Build fails on branch `origin/master` but build works fine on branch `origin/update-gradlew`
https://pastebin.com/4289srfu

**Comment by S-B99** [comment]
This is 100% related to me being dumb and just merging commits Willy Nilly. I will undo all of the unnecessary changes once I can. For now just use update-gradlew, it is ahead of 086s and works.

**Comment by S-B99** [comment]
Closing as I will be replacing master with features-master and all relevant updates
