### ISSUE TITLE
Add popbob dupe

### ISSUE THREAD

**Issue by S-B99** [S-B99/KAMI#248]

**Comment by Fu-ms** [comment]
package me.zeroeightsix.kami.module.modules.player;

import me.zeroeightsix.kami.module.Module;
import net.minecraft.client.Minecraft;
import net.minecraft.network.play.client.CPacketChatMessage;
import java.util.Random;

@Module.Info(name = "PopbobS3xDupe", description = "Automatically does the popbob sex dupe!", category = Module.Category.PLAYER)
public class PopbobS3xDupe extends Module {


    private static long startTime = 0;

    @Override
    public void onUpdate() {
        if (mc.player == null) {
            return;
        }

        else {
            if (startTime == 0) startTime = System.currentTimeMillis();
            if (startTime + 16000 <= System.currentTimeMillis()) {
                Minecraft.getMinecraft().playerController.connection.sendPacket(new CPacketChatMessage("I just completed the popbob sex dupe and got " + new Random().nextInt(200) + " new shulkers!"));
                startTime = System.currentTimeMillis();
            }
        }
    }
}

**Comment by Fu-ms** [comment]
https://pastebin.com/dZG2TfWW

**Comment by cookiedragon234** [comment]
Hmm wonder where you got that module code and idea from? @Fu-ms

Skid alert 👮‍♂️ Skid alert 👮‍♂️ Skid alert 👮‍♂️

**Comment by Fu-ms** [comment]
> Hmm wonder where you got that module code and idea from? @Fu-ms
> 
> Skid alert 👮‍♂️ Skid alert 👮‍♂️ Skid alert 👮‍♂️

Did you even read the fucking title or are you that ineducated you can't read yet?

**Comment by cookiedragon234** [comment]
Skids mad lmao!

**Comment by cookiedragon234** [comment]
Also love being “ineducated” greeeeeat one rofl

**Comment by Fu-ms** [comment]
> Skids mad lmao!

Arent you the faggot whos client got ripped 4 seperate times and had a paddy so you released a backdoored version of it and claimed you didnt do it?
