### ISSUE TITLE
gradle not here

### ISSUE THREAD

**Issue by d1gress** [S-B99/KAMI#269]
**Describe the bug**
gradle not here

**To Reproduce**
1. Go to repo
2. observe gradle not being here

**Expected behavior**
gradle here

**Additional context**
gradle need

**Comment by S-B99** [comment]
Duplicate of #192

**Comment by blockparole** [comment]
just use https://github.com/blockparole/KAMI-Green :P

**Comment by cookiedragon234** [comment]
^

**Comment by Vonr** [comment]
how about no
