### ISSUE TITLE
Remove sound reload

### ISSUE THREAD

**Issue by cookiedragon234** [S-B99/KAMI#284]
It’s been skidded

**Comment by S-B99** [comment]
ok

**Comment by S-B99** [comment]
it's not skidded ace wrote it and contributed

**Comment by cookiedragon234** [comment]
Anyone with half a brain cell can see it was copied straight out of a decompile.

1. Explicit casting down the inheritance tree (casting parameters to object)
2. Creating an explicit array for a vararg (“new String[]{”1”,”2”}” instead of “1,2”)

The fact that people get away with this baffles me

**Comment by S-B99** [comment]
i didn't even look at it ngl

**Comment by cookiedragon234** [comment]
Also it is *so* obvious it was skidded right from here: https://github.com/cookiedragon234/Backdoored-1.5-leak/blob/2fac6d335bc891f5ed20226b73a19b03b963816e/src/com/backdoored/hacks/misc/ReloadSoundSystem.java#L24 the code is identical 😂

**Comment by S-B99** [comment]
i never had sounds break on linux either, never heard of it before

**Comment by S-B99** [comment]
holy shit you had each module check for license lol

**Comment by S-B99** [comment]
never knew

**Comment by cookiedragon234** [comment]
Honestly can’t believe people have the audacity to skid modules so obviously and add them to open source clients, and the devs of those clients don’t even care

**Comment by S-B99** [comment]
sorry yes i did paste it atm editing something else ill push in 5 min

i never looked at it and just assumed they wrote it because they said they did, should've known better
