### ISSUE TITLE
Alpine doesnt work for some people like me

### ISSUE THREAD

**Issue by Vonr** [S-B99/KAMI#290]
**Describe the bug**
Alpine does not read packets for certain people such as me.

**To Reproduce**
1. Use alpine
2. Doesnt work

**Expected behavior**
Alpine should work duh

**Screenshots**

**Additional context**
Alpine listener does jackshit and cant read packets.

**Comment by Vonr** [comment]
maybe it has to do with having wireshark on my computer but highly unlikely

**Comment by S-B99** [comment]
duplicate of #268
