### ISSUE TITLE
this is the new general @everyone

### ISSUE THREAD

**Issue by Puffy120** [S-B99/KAMI#344]

**Comment by TheBritishMidget** [comment]
lol

**Comment by Itistheend** [comment]
this is the most efficient way to use discord

**Comment by TheBritishMidget** [comment]
very

**Comment by d1gress** [comment]
of course it is

**Comment by TheBritishMidget** [comment]
yes

**Comment by TheBritishMidget** [comment]
XD

**Comment by d1gress** [comment]
<@552213176582799372> help bella got sad and removed everyone's perms to talk

**Comment by TheBritishMidget** [comment]
lol

**Comment by TheBritishMidget** [comment]
lol

**Comment by TheBritishMidget** [comment]
XD

**Comment by d1gress** [comment]
<@563138570953687061> come back plssss

**Comment by d1gress** [comment]
<@552213176582799372> aaaaaaaaaaaaa help

**Comment by Itistheend** [comment]
hope this is just bella quitting kami. she seemed to be in a bad spot mentally.

**Comment by d1gress** [comment]
i dont understand why she would quit and not leave the discord

**Comment by J3r3myDE** [comment]
this is so sad, Alexa play Bitch lasagna
