### ISSUE TITLE
Speedmine

### ISSUE THREAD

**Issue by S-B99** [S-B99/KAMI#39]
Redacted as I have my own code written I forgot about

**Comment by 0-x-2-2** [comment]
GPL code is not compatible with LGPL.

**Comment by S-B99** [comment]
It's for reference, I'm rewriting it

**Comment by S-B99** [comment]
The xdolf repo doesn't even follow it's license honestly lul

**Comment by 0-x-2-2** [comment]
> It's for reference, I'm rewriting it

This does not matter.

> The xdolf repo doesn't even follow it's license honestly

What? The maintainers don't need to follow it because they still own the code even though it is licensed under GPL. Including MCP is just a violation of MCP copyright and including the files that MCP generated is a violation of Mojang's copyright.

**Comment by S-B99** [comment]
This repo is being relicensed in the near future hopefully. And where does it say LGPL code is not compatible with GPL?

LGPL is a "stick", if you will, version of GPL. It requires all projects using it's code to be licensed with GPL but minor conditions, such as keeping GPL. It shouldn't have been used for KAMI and I contacted 086 about it.

**Comment by S-B99** [comment]
@0-x-2-2 
`The GNU Lesser General Public License, version 3, is really the GNU General Public License version 3 plus some added extra permissions. GPL version 3 (section 7) says you can always remove added permissions, and by doing so you get the same code under the ordinary GNU GPL version 3. If a program permits use under GNU LGPL version 3 or later, you can relicense it to GPL version 3 or later; for each future GPL version N (N > 3), we will make an LGPL version N which consists of the GPL version N plus added permissions.`

https://www.gnu.org/licenses/license-compatibility.en.html

**Comment by 0-x-2-2** [comment]
> This repo is being relicensed in the near future hopefully. And where does it say LGPL code is not compatible with GPL?
> 
> LGPL is a "stick", if you will, version of GPL. It requires all projects using it's code to be licensed with GPL but minor conditions, such as keeping GPL. It shouldn't have been used for KAMI and I contacted 086 about it.

it is no longer possible to relicense KAMI to GPL because other people contributed under LGPL.

**Comment by S-B99** [comment]
It is possible if all the contributors agree to it.

**Comment by 0-x-2-2** [comment]
> It is possible if all the contributors agree to it.

Yeah, I doubt this will happen though,

**Comment by S-B99** [comment]
The change from LGPL to GPL is very minor

**Comment by S-B99** [comment]
FastBreak is already a thing. I'm dumb.
