### ISSUE TITLE
Customization discussion

### ISSUE THREAD

**Issue by Kamronboi** [S-B99/KAMI#413]
I think it would be good for the client if you added custom color settings and more visual settings in general. A lot of people only use impact for its AI along with the Visuals and if you were to get Visuals at least people wouldn't bother and would get baritone themselves with 1 less client to deal with.

**Comment by S-B99** [comment]
What specifically

**Comment by Kamronboi** [comment]
Chams: https://gyazo.com/9ec6cc26ae06915291a0affc4e7ab490

Crosshair: https://gyazo.com/2f1892810dfbeb0ab32883e866b7edad

ESP: https://gyazo.com/d8c4153cd059c3210f75ed54c273edfb https://gyazo.com/88c84186b3187ce3e29227b42982ea3d

StorageESP: https://gyazo.com/f82d5a1b596077bb82ee78e1ac8d1703

Tracers: https://gyazo.com/c0e9cbc2249658117672c24bec1f9bf5

Search: https://gyazo.com/6223433a70b637b0e6e09d941edb6492

The options that impact has for visuals alone is way more customization

**Comment by S-B99** [comment]
Chams is a no, I don't see what you want changed in your video. Crosshair can be done by texturepack or other mods.
What specifically about esp? Color probably has an issue here already.
Due to the limitations of kamis GUI having custom colors for all storage esp types is going to take a lot of work and is waiting for about ~5 issues right now related to GUI.
Tracers issue is a duplicate I think.
This doesn't have search.

Also not a ton of that is useful for anarchy. Only search and StorageESP from that list i'd say are useful, big maybe on tracers.

**Comment by Kamronboi** [comment]
I'm only saying this cause kamis colors are ass and I think people would enjoy being able to customize their client without needing multiple clients to do so and is a pain when colors change when adding friends and would have to add as friend for battle client and visual client.

**Comment by S-B99** [comment]
You mean, the color for adding friends in the chat is customizable? Is that what I'm getting here?

Also what colors specifically are bad? I can't add color options for literally every detail, saying "it's all bad" isn't very helpful yk

**Comment by Kamronboi** [comment]
No, no, no
People like making things match with their factions texture pack, GUI, Arrays, etc to fit in so not having customizeable options turns it off and people tend to use another client like impact for visual was Kami for Elytra and used to be for combat as well. 

The problem with this is that they would have to add someone to their friends list two times for both client, one for visual friend and another for combat friend.

**Comment by S-B99** [comment]
What do people use instead of blue for combat?

Also, please see [IronException/UniversalFriends/](https://github.com/IronException/UniversalFriends/)

And please see #372, #328, #195, #28, and #36

**Comment by Kamronboi** [comment]
Elementars b5.2 for combat as of right now

People use the EC of each of the Elementars Modules https://gyazo.com/62177729e4d87302e33da50ab5761732

**Comment by S-B99** [comment]
#129, auto web is really useless, i've said no to a better crystal aura until people tell me what specifically about it needs to be better, #154, and what are weakness attack and surroundec? 32ks are patched and it has the rest

**Comment by Kamronboi** [comment]
Pretty sure Weaknessattack is it focuses on people with weakness
SurroundEC is just a more customizable version of surround I suppose, 

I dont know what makes The CrystalAuraEC, SurroundEC, and AutoEC better than the Default on Both Elementars and Kami but I know they just work better when placing and more options.

**Comment by S-B99** [comment]
What's customizable about it ?

And what's autoac, and what more options?

I can't improve anything if I don't get feedback

**Comment by Kamronboi** [comment]
I showed it in the gif

If you want to see you can get the public jar and see how it feels compares to the current kami blue to see where kami can improve on

https://github.com/Elementars/Elementars-b5.2/releases

**Comment by S-B99** [comment]
You typed AutoEZ. See #129 

Kami Blue surround has all of that and more, except announcing usage. AutotrapEC is renamed Kami Blue autotrap

**Comment by S-B99** [comment]
I have elementars but I don't know what people like about other clients which is what I'm asking. I can't find the energy to even open minecraft outside of working on this so if you want something added I need what it is specifically.

**Comment by Kamronboi** [comment]
When I got time I will make two side by side videos showing how the crystal auras act in combat and perhaps will see.

**Comment by S-B99** [comment]
A video isn't as helpful as specific descriptions of what about it is better.

**Comment by Kamronboi** [comment]
I mean like I said it just feels better and works out better, I dont know why it just does so how could I describe it. It feels like it places better, I can control The hit and place range, Hit delay, Min damage so it isnt wasting. So im sure all these values will make it feel different than Kamis

**Comment by S-B99** [comment]
Thanks. Make a new issue to suggest stuff to improve about crystalaura as this is way offtopic, and literally turned into existing issues and that.
