### ISSUE TITLE
Auto32k TPS CPS speed

### ISSUE THREAD

**Issue by Brochacho5** [S-B99/KAMI#45]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cookiedragon234** [comment]
great issue you followed the template word for word!

**Comment by S-B99** [comment]
if one more person asks about this on discord i stg it's *soon :tm:*

working on it when i'll have time

**Comment by S-B99** [comment]
Having another option to automatically change it to TPS - 1 would be good

**Comment by blockparole** [comment]
assuming this ticket is about a delay setting for the attack aura, one could add something like:  
`private Setting<WaitMode> waitMode = register(Settings.e("Mode", WaitMode.TICK));`  
`private Setting<Double> waitTick = register(Settings.d("Tick Wait", 3.0));`  
`private int waitCounter;`  
...
aura loop:
`if (waitMode.getValue().equals(WaitMode.TICK) && waitTick.getValue() > 0) {
            if (waitCounter < waitTick.getValue()) {
                waitCounter++;
                return;
            } else {
                waitCounter = 0;
            }
        }`
...
`    private enum WaitMode {
        KAMI, TICK
    }`  

and replace existing calls to `wait.getValue()` with `waitMode.getValue().equals(WaitMode.KAMI)`.

**Comment by S-B99** [comment]
Solved in commit bdb5bd33ee31556947ed9f64e89b993c811c68a5
todo: turn it off after

**Comment by S-B99** [comment]
Added commit c25568defb2a004919418ffc16893401b6c2d5f2
This adds y offset

**Comment by S-B99** [comment]
Closed, all features finished in commit 61e782b94618f2cc36a0c61b2844f6b9c2a3161d
