### ISSUE TITLE
Kami blue auto placement issue

### ISSUE THREAD

**Issue by p0pb0b** [S-B99/KAMI#47]
When placing auto on 2b u need a 2 high wall wall behind u for it to place against. im assuming why is the placement isnt pointing at the top of the hopper making it place on the hopper. Any way to make a fix u can message me on discord im cyri we spoken before

**Comment by blockparole** [comment]
What Version did you test on?
Also, does it happen every time?
Is probably fixed in this [zeroeightysix/KAMI/pull/131](https://github.com/zeroeightysix/KAMI/pull/131).

**Comment by blockparole** [comment]
Also, never experienced this in testing, do you run another mod that, at the time of the bug being present manipulated player position?

**Comment by S-B99** [comment]
This was fixed in latest release
