### ISSUE TITLE
Aura 32k switch should grab 32k weapons from opened hoppers and move it into your hand

### ISSUE THREAD

**Issue by S-B99** [S-B99/KAMI#52]
Grab the inventory organizing from auto32k

**Comment by S-B99** [comment]
[See this to send the switch packet](https://github.com/S-B99/KAMI/blob/4b737aa1b875394e183f3d0e2d9ce30c023d39e9/src/main/java/me/zeroeightsix/kami/module/modules/combat/Auto32k.java#L267)

TL:DR from my convo with hub: copy code from auto32k lol

**Comment by blockparole** [comment]
[check](https://wiki.vg/Inventory#Player_Inventory) [these](https://wiki.vg/Inventory#Hopper)
