### ISSUE TITLE
Bind mouse support

### ISSUE THREAD

**Issue by S-B99** [S-B99/KAMI#53]
.bind should support stuff like `mouse4` and `mouse5`, i'll look into how 086 wrote it

**Comment by S-B99** [comment]
code is bleh and it looks like there aren't real forge / minecraft mappings available to support this
as @cookiedragon234 suggested in discord use a macro

**Comment by cookiedragon234** [comment]
As you can see here: https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes?redirectedfrom=MSDN most operating systems only have key codes for 5 mouse buttons. Three of these are taken up by left, middle and right key. The other two are for side mouse buttons. Any more than two mouse buttons simple cannot be interpreted by programs. The only way around this is to use something like razer synapse to macro them to a keyboard key.

**Comment by S-B99** [comment]
And I'm not bothering to code something to check if you're on windows or linux and then support both individually even just for those 2 buttons
