### ISSUE TITLE
Auto32k doesn't work on 2b

### ISSUE THREAD

**Issue by S-B99** [S-B99/KAMI#59]
This is because 2b doesn't send shulker packets until you opened it properly eg .peek doesn't work

Todo: add seperate option to bypass the 32ks in shulker check with a warning in chat

**Comment by S-B99** [comment]
Apparently it doesn't even check so closing this as the person reporting it didn't follow up and I cannot reproduce this on my own, with and without 086's KAMI

**Comment by blockparole** [comment]
I cant reproduce this either, could add y offset max range setting for cornercases.
