### ISSUE TITLE
Aura autoswitch

### ISSUE THREAD

**Issue by S-B99** [S-B99/KAMI#60]
Autoswitch seperate from 32k switch to make sure 32k switch is not on

**Comment by blockparole** [comment]
already commented the code at the particular [line](https://github.com/S-B99/KAMI/blob/0e6a7911017b63f0ad1c17c42b18f93178181cfb/src/main/java/me/zeroeightsix/kami/module/modules/combat/Aura.java#L86)

`                    if (!switchTo32k.getValue() && ModuleManager.isModuleEnabled("AutoTool")) {
                        AutoTool.equipBestWeapon();
                    }`

**Comment by blockparole** [comment]
Autoswitch is done atm by `AutoTool.equipBestWeapon();`, only if `ModuleManager.isModuleEnabled("AutoTool")`, 32k switch doesnt use it cause it could be either:  
a) AutoTool not active
b) 32k is not a Weapon or Tool

**Comment by S-B99** [comment]
I meant to prefer autoswitch for 32ks, even when it's on so it's more convenient for the user. And ty, i'll take a look at it

**Comment by S-B99** [comment]
Can someone help me explain what the hell this was for? I can't understand the title

**Comment by S-B99** [comment]
Is this just autoswitch but not 32k specific? If so then just rename 32k switch to that and give 32ks priority
