### ISSUE TITLE
Placement improvements for Auto32k

### ISSUE THREAD

**Issue by ub3rshadow** [S-B99/KAMI#76]
- [ ] PlaceAtCursor - Places hopper and shulker at location of the cursor rather than finding an ideal location.

- [x] DisableWhenPlaced - Disables auto32k after it has been used.

**Comment by S-B99** [comment]
Auto32k is already disabled once closed, unless you mean #64

**Comment by S-B99** [comment]
CrystalAura has a way to check where you're using to place so you can use that
