### ISSUE TITLE
HopperNuker (q)

### ISSUE THREAD

**Issue by DontEatOreo** [S-B99/KAMI#83]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Whenever there is a hopper, the feature will prioritize itself. For example, if you're crystaling, you will stop doing that and begin destroying hoppers, and after all of them are destroyed, you could return to crystaling.

**Describe alternatives you've considered**

**Additional context**

**Comment by S-B99** [comment]
Closed as duplicate
