### ISSUE TITLE
Auto32k Bypass

### ISSUE THREAD

**Issue by ub3rshadow** [S-B99/KAMI#87]
Places a dispenser next to hopper, puts 32k shulker into dispenser and then dispenses it by placing a redstone block next to it. Raion client has this now and it's frustrating that people are starting to 32k at spawn again.

**Comment by S-B99** [comment]
I need an image of where everything goes

**Comment by S-B99** [comment]
![](https://cdn.discordapp.com/attachments/634010802403409931/644270468206952448/unknown.png)

**Comment by blockparole** [comment]
I made this depiction :3
![](https://i.imgur.com/a7v1qfh.png)

**Comment by ub3rshadow** [comment]
Correction for the screenshot i took: Redstone block can be anywhere adjacent to the dispenser except for a position where it would be in contact with the hopper, eg below the dispenser or directly above the hopper, as it would prevent the hopper from collecting the 32ks.

**Comment by S-B99** [comment]
lever and block modes are possible then

**Comment by blockparole** [comment]
also flint n steel

**Comment by ub3rshadow** [comment]
Levers and buttons would work too, but they'd take up more space and need placing then activating making them slower. Buttons make levers obsolete since they disable themselves, but again eating up even more time.

**Comment by blockparole** [comment]
i guess my suggestion would make an elegant implementation for this :P
redstone compiler -> schematic file

**Comment by ub3rshadow** [comment]
> i guess my suggestion would make an elegant implementation for this :P
> redstone compiler -> schematic file

A schematic of sorts would work however the dispenser can be on any side of the hopper, and the power source could be on almost any side of the dispenser. I imagine this would be difficult to code and probably not worth it in most scenarios.

**Comment by blockparole** [comment]
yeah just trolling sorry 🙈 
so for the actual code, wouldnt be too much of a refactor.
add additional logic [here](https://github.com/S-B99/KAMI/blob/051a9e8fd6a7d5c1da20deb5de57029a57eb552b/src/main/java/me/zeroeightsix/kami/module/modules/combat/Auto32k.java#L304), with checks for the 4 horizontals of the hopper and for the potential power source location, depending on mode.
and some additional logic for the power source and dispenser [here](https://github.com/S-B99/KAMI/blob/051a9e8fd6a7d5c1da20deb5de57029a57eb552b/src/main/java/me/zeroeightsix/kami/module/modules/combat/Auto32k.java#L88).
Then add prior stage for [this](https://github.com/S-B99/KAMI/blob/051a9e8fd6a7d5c1da20deb5de57029a57eb552b/src/main/java/me/zeroeightsix/kami/module/modules/combat/Auto32k.java#L265), which, when in lever mode, activates the lever.

**Comment by DragonSlayerXVX** [comment]
i keep crashing when i use it did i do something wrong?

**Comment by S-B99** [comment]
You mean the client? Please ask for help on discord or make an issue
