### ISSUE TITLE
Autotrap (q)

### ISSUE THREAD

**Issue by S-B99** [S-B99/KAMI#89]

**Comment by Crystallinqq** [comment]
nickgur

**Comment by Deauthorized** [comment]
seems like a good idea, maybe have it be toggle-able and have it automatically trap any players who come into block placing range lol

**Comment by S-B99** [comment]
I mean, that is what it's for

**Comment by Mello-Gamer** [comment]
bruh

**Comment by Deauthorized** [comment]
> 
> 
> I mean, that is what it's for

i made this comment at 4 am have mercy

**Comment by Deauthorized** [comment]
also #124 could probably override this so when someone is trapped mine the obsidian besides their feet and automatically explodey boom boom them
