### ISSUE TITLE
AutoTrap/AutoObby/PlayerSurrounder

### ISSUE THREAD

**Issue by DontEatOreo** [S-B99/KAMI#93]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It places obsidian around players.
**Describe alternatives you've considered**

**Additional context**
Screenshot of a simple design: https://i.imgur.com/mvI3nTE.png or possible just kami attempts to place blocks until it completely boxed the player no matter what.

**Comment by S-B99** [comment]
Please use more then one issue per more then one feature, and see #59
